/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calculadora;

/**
 *
 * @author caio
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entradaValor = new javax.swing.JSpinner();
        lblResto = new javax.swing.JLabel();
        lblCubo = new javax.swing.JLabel();
        lblRaiz = new javax.swing.JLabel();
        lblRCubica = new javax.swing.JLabel();
        lblAbsoluto = new javax.swing.JLabel();
        lblRestoResultado = new javax.swing.JLabel();
        lblCuboResultado = new javax.swing.JLabel();
        lblRaizResultado = new javax.swing.JLabel();
        lblRCubicaResultado = new javax.swing.JLabel();
        lblAbsolutoResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/calculadora/imagens/botaocalculadora35x35.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/calculadora/imagens/calculadora150x150.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel2.setText("Informe um valor:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel3.setText("Super Calculadora");

        entradaValor.setModel(new javax.swing.SpinnerNumberModel(1, -50, null, 1));

        lblRestoResultado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblRestoResultado.setForeground(new java.awt.Color(0, 153, 153));

        lblCuboResultado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblCuboResultado.setForeground(new java.awt.Color(0, 153, 153));

        lblRaizResultado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblRaizResultado.setForeground(new java.awt.Color(0, 153, 153));

        lblRCubicaResultado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblRCubicaResultado.setForeground(new java.awt.Color(0, 153, 153));

        lblAbsolutoResultado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblAbsolutoResultado.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(entradaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResto)
                            .addComponent(lblCubo)
                            .addComponent(lblRaiz)
                            .addComponent(lblRCubica)
                            .addComponent(lblAbsoluto))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRestoResultado)
                            .addComponent(lblCuboResultado)
                            .addComponent(lblRaizResultado)
                            .addComponent(lblRCubicaResultado)
                            .addComponent(lblAbsolutoResultado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(entradaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResto)
                            .addComponent(lblRestoResultado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCubo)
                            .addComponent(lblCuboResultado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaiz)
                            .addComponent(lblRaizResultado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRCubica)
                            .addComponent(lblRCubicaResultado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAbsoluto)
                            .addComponent(lblAbsolutoResultado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        float numeroBase = Float.parseFloat(entradaValor.getValue().toString());
        int numeroBaseInt = Integer.parseInt(entradaValor.getValue().toString());
        lblResto.setText("Resto da Divisão por 2:");
        lblCubo.setText("Elevado ao Cubo:");
        lblRaiz.setText("Raiz Quadrada:");
        lblRCubica.setText("Raiz Cúbica:");
        lblAbsoluto.setText("Valor Absoluto:");
        //float resto = numeroBase%2;
        lblRestoResultado.setText(Integer.toString((int)numeroBase%2));
        lblCuboResultado.setText(Integer.toString((int) Math.pow(numeroBase, 3)));
        //lblRaizResultado.setText(Float.toString((float) Math.sqrt(numeroBase)));
        lblRaizResultado.setText(String.format("%.2f", Math.sqrt(numeroBase)));
        //lblRCubicaResultado.setText(Float.toString((float)Math.cbrt(numeroBase)));
        lblRCubicaResultado.setText(String.format("%.2f", Math.cbrt(numeroBase)));
        lblAbsolutoResultado.setText(Integer.toString((int)Math.abs(numeroBase)));
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JSpinner entradaValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAbsoluto;
    private javax.swing.JLabel lblAbsolutoResultado;
    private javax.swing.JLabel lblCubo;
    private javax.swing.JLabel lblCuboResultado;
    private javax.swing.JLabel lblRCubica;
    private javax.swing.JLabel lblRCubicaResultado;
    private javax.swing.JLabel lblRaiz;
    private javax.swing.JLabel lblRaizResultado;
    private javax.swing.JLabel lblResto;
    private javax.swing.JLabel lblRestoResultado;
    // End of variables declaration//GEN-END:variables
}
